// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Model.Zocalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadArchivos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTamano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinTamano")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PromedioDuracion")
                        .HasColumnType("REAL");

                    b.Property<double>("PromedioTamañoArchivos")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("zocalos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
